In [1]:
import pandas as pd
df_grupos = pd.read_csv('./data/mrsat_grupos.csv')
df = pd.read_csv('./data/mrsat_hist.csv', converters = {'AgenteCausal1':str, 'CelMl1':str, 'AgenteCausal2':str, 'AgenteCausal3':str})

In [2]:
df

,ID,Folio,CodigoAnalisis,DescripcionAnalisis,Resultado,CodigoArea,DescripcionArea,CodigoCentro,DescripcionCentro,CodigoBancoNatural,...,AgenteCausal3,CelMl3,RED3,AgenteCausal4,CelMl4,RED4,AgenteCausal5,CelMl5,RED5,FechaActualización
0,1,601277,5,RED CUALITATIVA,2.0,10304,Quellón Viejo,102978,QUELLON VIEJO 5,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-16
1,2,601277,6,INTEGRADA CUANTITATIVA,0.0,10304,Quellón Viejo,102978,QUELLON VIEJO 5,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-16
2,3,601278,5,RED CUALITATIVA,2.0,10304,Quellón Viejo,102057,QUELLÓN 3 M JARAMILLO SANZ 102057,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-16
3,4,601278,6,INTEGRADA CUANTITATIVA,0.0,10304,Quellón Viejo,102057,QUELLÓN 3 M JARAMILLO SANZ 102057,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-16
4,5,601279,1,VPM,0.0,10304,Quellón Viejo,102978,QUELLON VIEJO 5,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177579,194121,650801,6,INTEGRADA CUANTITATIVA,0.0,10324,Estero Lingue,102022,ESTERO LINGUE,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 14:22:00.870
177580,194122,650984,5,RED CUALITATIVA,0.0,10490,Punta Quillaipe,103551,Punta Quillaipe,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 14:22:00.870
177581,194123,650984,6,INTEGRADA CUANTITATIVA,0.0,10490,Punta Quillaipe,103551,Punta Quillaipe,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 14:22:00.870
177582,194124,650985,1,VPM,30.0,10490,Punta Quillaipe,103551,Punta Quillaipe,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 14:22:00.870
177583,194125,650417,20,E. COLI B,20.0,10535,Estero Chauquear II,102081,ESTERO CHAUQUEAR,0,...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 14:22:00.870